### PR TITLE
Next version ClashTui in Linux.

### PR DESCRIPTION
**Pull request by JohanChane**
I have developed and refined a version under your dev branch. I feel you have made a tremendous contribution to clashtui. I would like to invite you as collaborators on clashtui, to develop and enhance clashtui together with me. Currently, this pr only completes the Linux platform.

With the addition of features, I feel it's time to separate the code for the Linux platform and the Windows platform (Linux being the primary one, with basic functionality for Windows being sufficient), creating two branches for Linux and Windows. There will also be a development branch where we'll first submit the code, and once testing or development is completed, we'll move it to the stable version branch. This is what I'm going to do next.

You are free to develop and design the project at your discretion. I have no specific requirements. Just have fun with it.

### CODE REVIEW

**Comment by Jackhr-arch** [comment]
It seems that you haven't finished yet, so I will convert this to draft

**Comment by JohanChane** [comment]
I have invited you to be a collaborator for clashtui. Can you receive the message?

**Comment by Jackhr-arch** [comment]
After this pr is done, I'll do :)

**Comment by JohanChane** [comment]
I have tested all the features of my dev branch clashtui in Linux, but it includes code for the Windows platform. I am separating the code for Linux and Windows platforms.

**Comment by JohanChane** [comment]
I have done.

**Comment by Jackhr-arch** [comment]
Well, I perfer to combine them in one for better coding experience. Anyway I will approve this pr and fix it later.

**Comment by JohanChane** [comment]
I haven't implemented the new features for Windows yet. I plan to trim down some code and focus on fixing bugs. I feel that Windows doesn't require too many additional features.

**Pull request merged**
